name: "Test ENV variables"

on:
  workflow_dispatch:

permissions: write-all

jobs:  
 one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ tojson(secrets) }}
        run: echo "$GITHUB_CONTEXT"
