name: "Test ENV variables"

on:
  workflow_dispatch:

permissions: write-all

jobs:  
 one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ secrets.NUGET_GITHUB_PAT }}
        run: echo "$GITHUB_CONTEXT"
